name: Release
on:
  release:
    types: [created]

jobs:
  build-on-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Copy executable
      run: |
        for TOOL in genoStats pileupCaller vcf2eigenstrat; do
          docker cp linuxcontainer:/root/.local/bin/$TOOL $TOOL-linux
        done
    - name: update-release
      run: |
        for TOOL in genoStats pileupCaller vcf2eigenstrat; do
          bash .github/workflows/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=stschiff repo=sequenceTools tag=$(basename $GITHUB_REF) filename=$TOOL-linux
        done
  build-on-mac:
    runs-on: macos-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
    - name: Build
      run: stack install
    - name: Update-release
      run: |
        for TOOL in genoStats pileupCaller vcf2eigenstrat; do
          cp ~/.local/bin/$TOOL $TOOL-macOS
          bash .github/workflows/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=stschiff repo=sequenceTools tag=$(basename $GITHUB_REF) filename=$TOOL-macOS
        done
  build-on-windows:
    runs-on: windows-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Setup Haskell
      uses: haskell/actions/setup@v1
      with:
        enable-stack: true
    - name: Build
      run: stack install
    - name: Update-release
      run: |
        for TOOL in genoStats pileupCaller vcf2eigenstrat; do
          cp ~/.local/bin/$TOOL $TOOL-windows
          bash .github/workflows/upload-github-release-asset.sh github_api_token=${{ secrets.GITHUB_TOKEN }} owner=stschiff repo=sequenceTools tag=$(basename $GITHUB_REF) filename=$TOOL-windows
        done
